Fixed CentOS stream HA repo
OndrejHome/ansible.ha-cluster-pacemaker pull request #14
Opened 2020-12-21 13:53 UTC by iqfx

I tried this role out on centos 8 stream and it didn't modify the repo's properly.

I have tested this role and it behaves as expected.

I had to use ignore_errors because unortunately ansible cannot distinguish centos 8 from centos stream.

If there is a better way to do it then I will obviously try to correct this.

2020-12-22 13:00 UTC, OndrejHome requested changes
Hello Quint (@iqfx ),

Thank you for using this role a proposing the change for CentOS Stream repositories. Based on quick testing I think that it should be possible to distinguish CentOS Linux from CentOS Stream based on `ansible_distribution_version` value and therefore remove the `ignore_errors: yes` statements. Please see my comments in PR for more details.

Could you please adjust the PR to use this alternative approach? 
Thank you for you effort!

Ondrej (온드레이)

2020-12-22 13:00 UTC, OndrejHome commented on tasks/centos_repos.yml
> +  ignore_errors: yes
I would definitely like to avoid this.

2020-12-22 13:00 UTC, OndrejHome commented on tasks/centos_repos.yml
> +    and ansible_distribution_version not in ['8.0', '8.1', '8.2']
This will unfortunately match CentOS 8.3 which will fail as the *-Stream-* repo file is not there. However checking out the facts from CentOS 8.3 and CentOS Stream 8 reveals one possible solution:
- `ansible_distribution_version == '8'` - matches CentOS Stream 8
- `ansible_distribution_version in ['8.0', '8.1', '8.2', '8.3']`- atches CentOS Linux 8.0, 8.1, 8.2, 8.3

Could you please update this task to match the CentOS stream based on above rule and remove the ` ignore_errors: true` as that should be then not needed?

2020-12-22 13:00 UTC, OndrejHome commented on tasks/centos_repos.yml
>      and ansible_distribution_version not in ['8.0', '8.1', '8.2']
Check comment later that explains how to  exclude the CentOS Stream from here.

2020-12-22 14:25 UTC, iqfx commented on tasks/centos_repos.yml
> +  ignore_errors: yes
I have managed to use your advice in the below comment in order to distuingish centos stream and centos 8.3.

2020-12-22 14:26 UTC, iqfx commented on tasks/centos_repos.yml
> +    and ansible_distribution_version not in ['8.0', '8.1', '8.2']
I had to had the '8' versiona in order to make sure it doesn't trigger on centos stream.

2020-12-23 14:33 UTC, merged

2020-12-23 14:37 UTC, OndrejHome commented
Hello Quint (@iqfx ),
Thank you for changes and your contribution! 
I plan to do some additional testing before creating new tag. I will let you know when that is done and new tag is added here. 
Enjoy the upcoming holidays in peace and safety.

Ondrej (온드레이)

2020-12-24 00:35 UTC, iqfx commented
Thanks @OndrejHome !

Wishing you happy holidays as well!
Also stay safe while this bizarre year comes to an end.

2020-12-28 01:45 UTC, OndrejHome commented
new tag `27.0.0` was released with the changes from this PR and got imported to [Ansible galaxy](https://galaxy.ansible.com/OndrejHome/ha-cluster-pacemaker). Please note that Ansible version 2.9.16/2.10.4 or newer is needed for `service` module to properly work on CentOS 8 Stream due to https://github.com/ansible/ansible/issues/71528. I have added information about this to README. Ansible 2.8.x should work for any other OS versions that this role supports.

In case you run into any new issues with role feel free to rise Issue or PR anytime.

Once again, Thank you @igfx for contribution and as you said very well - stay safe!